In [41]:
import numpy as np
from numpy.random import random as rnd 
import pandas as pd

In [20]:
class parameters:
    def __init__(self,n):
        self.mu = rnd((n,1))
        self.F = rnd((n,n))
        self.R = rnd((1,1))
        self.q = rnd((n,n))
        self.Q = self.q.T@self.q
        self.beta00 = rnd((n,1))
        self.p00 = rnd((n,n))
        self.P00 = self.p00.T@self.p00
        

In [21]:
par = parameters(3)

In [22]:
par.Q

array([[1.02205495, 0.53989789, 0.11059316],
       [0.53989789, 0.47758369, 0.22839307],
       [0.11059316, 0.22839307, 0.22989231]])

In [23]:
par.__dict__

{'mu': array([[0.40233191],
        [0.76584701],
        [0.34320699]]),
 'F': array([[0.55061662, 0.33113892, 0.61502126],
        [0.56004203, 0.55551583, 0.04568087],
        [0.34407864, 0.41828728, 0.03733822]]),
 'R': array([[0.09038108]]),
 'q': array([[0.17686942, 0.46068514, 0.20877895],
        [0.98587039, 0.42433492, 0.01467627],
        [0.13722872, 0.29204926, 0.43137949]]),
 'Q': array([[1.02205495, 0.53989789, 0.11059316],
        [0.53989789, 0.47758369, 0.22839307],
        [0.11059316, 0.22839307, 0.22989231]]),
 'beta00': array([[0.41405291],
        [0.59682839],
        [0.21172156]]),
 'p00': array([[0.02398415, 0.14558323, 0.52534352],
        [0.010373  , 0.60228505, 0.0955615 ],
        [0.87339421, 0.89044025, 0.22651296]]),
 'P00': array([[0.76350028, 0.78744455, 0.21142628],
        [0.78744455, 1.17682561, 0.33573273],
        [0.21142628, 0.33573273, 0.33642593]])}

In [29]:
class parameters:
    def __init__(self,n):
        self.mu = rnd((n,1))
        self.F = rnd((n,n))
        self.R = rnd((1,1))
        self.q = rnd((n,n))
        self.Q = self.q.T@self.q
        self.beta00 = rnd((n,1))
        self.p00 = rnd((n,n))
        self.P00 = self.p00.T@self.p00

class data:
    def __init__(self,n):
        self.y = rnd((1,1))
        self.x = rnd((1,n))
        
class prediction:
    def __init__(self,n):
        self.beta = rnd((n,1))
        self.P = rnd((n,n))
        self.eta = rnd((1,1))
        self.f = rnd((1,1))
        
class updating:
    def __init__(self,n):
        self.beta = rnd((n,1))
        self.P = rnd((n,n))
        self.K = rnd((n,1))
        
class a_period:
    def __init__(self,t,n):
        self.t = t
        self.data = data(n)
        self.prd = prediction(n)
        self.upd = updating(n)
        
class the_model:
    def __init__(self,n,T):
        self.pars = parameters(n)
        self.sample = []
        for t in range(T): self.sample.append(a_period(t,n))
# The line above is an abbreviation of these three lines:
#        for t in range(T):
#            new_period = a_period(t,n)
#            self.sample.append(new_period)
        
        

In [30]:
ibm = the_model(3,120)

In [33]:
ibm.pars.__dict__

{'mu': array([[0.65748594],
        [0.69132732],
        [0.30571532]]),
 'F': array([[0.22765992, 0.92823554, 0.51259424],
        [0.72797496, 0.68052584, 0.35279226],
        [0.71157508, 0.37521517, 0.89795728]]),
 'R': array([[0.26352706]]),
 'q': array([[0.03805094, 0.52104713, 0.36842888],
        [0.90239695, 0.29678749, 0.83545277],
        [0.04050159, 0.65719211, 0.06200802]]),
 'Q': array([[0.8174085 , 0.31426378, 0.77044051],
        [0.31426378, 0.7914744 , 0.48067192],
        [0.77044051, 0.48067192, 0.83756616]]),
 'beta00': array([[0.02598452],
        [0.79829365],
        [0.23435476]]),
 'p00': array([[0.42111083, 0.82117505, 0.20758875],
        [0.29514472, 0.78921363, 0.20038412],
        [0.30267092, 0.56580241, 0.1799323 ]]),
 'P00': array([[0.35605443, 0.74998988, 0.20102047],
        [0.74998988, 1.61731898, 0.43041872],
        [0.20102047, 0.43041872, 0.11562252]])}

In [36]:
ibm.sample[25].__dict__

{'t': 25,
 'data': <__main__.data at 0x7f86dc180ad0>,
 'prd': <__main__.prediction at 0x7f86dc180cd0>,
 'upd': <__main__.updating at 0x7f86dc180550>}

In [37]:
ibm.sample[25].data.__dict__

{'y': array([[0.37481857]]),
 'x': array([[0.02924797, 0.34054305, 0.15217015]])}

In [40]:
ibm.sample[25].data.y

array([[0.37481857]])

In [83]:
import numpy as np
from numpy.random import random as rnd 
import pandas as pd

class parameters:
    def __init__(self,n):
        self.mu = rnd((n,1))
        self.F = rnd((n,n))
        self.R = rnd((1,1))
        self.q = rnd((n,n))
        self.Q = self.q.T@self.q
        self.beta00 = rnd((n,1))
        self.p00 = rnd((n,n))
        self.P00 = self.p00.T@self.p00

class data:
    def __init__(self,n):
        self.y = rnd((1,1))
        self.x = rnd((1,n))
        
class prediction:
    def __init__(self,n):
        self.beta = rnd((n,1))
        self.P = rnd((n,n))
        self.eta = rnd((1,1))
        self.f = rnd((1,1))
        
class updating:
    def __init__(self,n):
        self.beta = rnd((n,1))
        self.P = rnd((n,n))
        self.K = rnd((n,1))
        
class a_period:
    def __init__(self,t,n):
        self.t = t
        self.data = data(n)
        self.prd = prediction(n)
        self.upd = updating(n)
        
class the_model:
    def __init__(self,datafile):
        self.datafile = datafile
        df = pd.read_csv(datafile)
        T,n = df.shape
        n = n - 1
        self.pars = parameters(n)
        self.sample = []
        for t in range(T): 
            new_period = a_period(t,n)
            new_period.data.y = np.array([[ df.iloc[t,0] ]])
            new_period.data.x = df.iloc[t,1:].values.reshape((1,n))
            self.sample.append(new_period)
        
        

In [84]:
ibm = the_model("IBM.csv")

In [85]:
ibm.sample[3].data.x

array([[ 0.0421, -0.0123, -0.0051]])

In [86]:
ibm.sample[3].data.y

array([[0.011225]])

In [87]:
type(ibm)

__main__.the_model

In [97]:
import numpy as np
from numpy.random import random as rnd 
import pandas as pd
from numpy.linalg import inv as ii

class parameters:
    def __init__(self,n):
        self.mu = rnd((n,1))
        self.F = rnd((n,n))
        self.R = rnd((1,1))
        self.q = rnd((n,n))
        self.Q = self.q.T@self.q
        self.beta00 = rnd((n,1))
        self.p00 = rnd((n,n))
        self.P00 = self.p00.T@self.p00

class data:
    def __init__(self,n):
        self.y = rnd((1,1))
        self.x = rnd((1,n))
        
class prediction:
    def __init__(self,n):
        self.beta = rnd((n,1))
        self.P = rnd((n,n))
        self.eta = rnd((1,1))
        self.f = rnd((1,1))
        
class updating:
    def __init__(self,n):
        self.beta = rnd((n,1))
        self.P = rnd((n,n))
        self.K = rnd((n,1))
        
class a_period:
    def __init__(self,t,model):
        self.t = t
        self.mymodel = model
        n = self.mymodel.n
        self.data = data(n)
        self.prd = prediction(n)
        self.upd = updating(n)
    def predict(self):
        par = self.mymodel.pars
        mu = par.mu
        F = par.F
        if self.t == 0: 
            b = par.beta00
            P = par.P00
        else:
            previous_period = self.mymodel.sample[self.t-1]
            b = previous_period.upd.beta
            P = previous_period.upd.P
        self.prd.beta = mu + F @ b
        self.prd.P = (F @ P) @ F.T + par.Q
        x = self.data.x
        self.prd.eta = self.data.y - x @ self.prd.beta
        self.prd.f = (x @ self.prd.P) @ x.T + par.R
    def update(self):
        P = self.prd.P
        x = self.data.x
        K = (P @ x.T) @ ii(self.prd.f)
        self.upd.K = K
        self.upd.beta = self.prd.beta + K @ self.prd.eta
        self.upd.P = P - (K @ x) @ P
            
class the_model:
    def __init__(self,datafile):
        self.datafile = datafile
        df = pd.read_csv(datafile)
        T,n = df.shape
        n = n - 1
        self.n = n
        self.T = T
        self.pars = parameters(n)
        self.sample = []
        for t in range(T): 
            new_period = a_period(t,self)
            new_period.data.y = np.array([[ df.iloc[t,0] ]])
            new_period.data.x = df.iloc[t,1:].values.reshape((1,n))
            self.sample.append(new_period)
    def run(self):
        for t in range(self.T):
            self.sample[t].predict()
            self.sample[t].update()
        
        

In [98]:
ibm = the_model("IBM.csv")

In [99]:
ibm.run()

In [101]:
for aperiod in ibm.sample: print(aperiod.upd.beta.T)

[[0.88764463 1.24460285 0.43641917]]
[[2.62045012 2.78875005 1.0712048 ]]
[[4.60414275 4.46826176 1.61154242]]
[[8.18584981 7.46470339 2.50280251]]
[[12.74698738 11.26570337  3.54491378]]
[[4.5212745  4.44871809 1.82491675]]
[[5.67945992 5.43285545 2.19187683]]
[[4.38504605 4.37994399 2.00811695]]
[[3.6421137  3.78324536 1.94524009]]
[[5.16901163 5.06154311 2.34339382]]
[[4.97590143 4.91239731 2.35971666]]
[[10.43675836  9.44207693  3.5460252 ]]
[[0.19610906 0.97562479 1.45020099]]
[[1.27139866 1.86736594 1.68830922]]
[[4.12975406 4.24083118 2.31953112]]
[[8.53534772 7.890949   3.25865938]]
[[8.35997915 7.74416128 3.2155189 ]]
[[5.182108   5.11723615 2.56702601]]
[[10.54867501  9.56081034  3.70145934]]
[[19.3847113  16.87434767  5.54510719]]
[[9.92380142 9.04971941 3.59409503]]
[[4.67272536 4.70871539 2.52264725]]
[[3.16788826 3.46605331 2.2222963 ]]
[[-0.2496051   0.64208481  1.52912932]]
[[1.46760565 2.0617754  1.88808196]]
[[4.09246494 4.23622486 2.44091459]]
[[9.24980551 8.50365166

<h3>Scratchwork:</h3>

In [5]:
rnd((3,5))

array([[0.27596871, 0.03173192, 0.16616511, 0.98405557, 0.80877311],
       [0.81609058, 0.1835191 , 0.44784052, 0.61797826, 0.16938288],
       [0.37717612, 0.44790398, 0.50499714, 0.4368338 , 0.88229915]])

In [8]:
a = -3

In [9]:
b = a*a

In [10]:
b

9

In [11]:
c = 3

In [12]:
c*c

9

In [13]:
q = rnd((3,3))

In [14]:
q

array([[0.34349119, 0.05150247, 0.25161358],
       [0.185515  , 0.39124997, 0.28190982],
       [0.00400654, 0.44393206, 0.68077661]])

In [15]:
(q.T) @ q

array([[0.15241807, 0.09205202, 0.14145311],
       [0.09205202, 0.35280472, 0.42547449],
       [0.14145311, 0.42547449, 0.60623933]])

In [16]:
q.T@q

array([[0.15241807, 0.09205202, 0.14145311],
       [0.09205202, 0.35280472, 0.42547449],
       [0.14145311, 0.42547449, 0.60623933]])

In [17]:
q

array([[0.34349119, 0.05150247, 0.25161358],
       [0.185515  , 0.39124997, 0.28190982],
       [0.00400654, 0.44393206, 0.68077661]])

In [18]:
q.T

array([[0.34349119, 0.185515  , 0.00400654],
       [0.05150247, 0.39124997, 0.44393206],
       [0.25161358, 0.28190982, 0.68077661]])

In [42]:
d = pd.read_csv('IBM.csv')

In [43]:
d.head()

IBM-rf  Mkt-rf     HML     SMB
0  0.115265  0.1358  0.0806  0.1093
1  0.146888  0.0541 -0.0452  0.0023
2 -0.043500  0.0261  0.0254  0.0374
3  0.011225  0.0421 -0.0123 -0.0051
4  0.026369  0.0507 -0.0426  0.0391

In [44]:
type(d)

pandas.core.frame.DataFrame

In [45]:
d.iloc[1,1]

0.0541

In [46]:
d.iloc[1,]

IBM-rf    0.146888
Mkt-rf    0.054100
HML      -0.045200
SMB       0.002300
Name: 1, dtype: float64

In [47]:
d.iloc[1,].values

array([ 0.14688791,  0.0541    , -0.0452    ,  0.0023    ])

In [49]:
d.shape

(405, 4)

In [50]:
one_row = d.iloc[1,].values

In [51]:
one_row.shape

(4,)

In [52]:
ibm.sample[25].data.x.shape

(1, 3)

In [53]:
one_row.reshape((1,4))

array([[ 0.14688791,  0.0541    , -0.0452    ,  0.0023    ]])

In [54]:
one_row

array([ 0.14688791,  0.0541    , -0.0452    ,  0.0023    ])

In [57]:
t = 25

In [59]:
df = pd.read_csv("IBM.csv")
a_row = df.iloc[t,1:]

In [60]:
a_row

Mkt-rf   -0.0193
HML       0.0050
SMB       0.0108
Name: 25, dtype: float64

In [61]:
type(a_row)

pandas.core.series.Series

In [62]:
a_row.values

array([-0.0193,  0.005 ,  0.0108])

In [64]:
a_row.values.reshape((1,3))

array([[-0.0193,  0.005 ,  0.0108]])

In [67]:
df.iloc[t,0]

0.009

In [69]:
a1 = np.array([[   df.iloc[t,0]   ]])

In [70]:
a2 = np.array([   df.iloc[t,0]   ])

In [71]:
a3 = np.array(   df.iloc[t,0]   )

In [72]:
a1

array([[0.009]])

In [73]:
a2

array([0.009])

In [74]:
a3

array(0.009)

In [75]:
type(a3)

numpy.ndarray

In [76]:
type(a2)

numpy.ndarray

In [77]:
type(a1)

numpy.ndarray

In [78]:
a1.shape

(1, 1)

In [79]:
a2.shape

(1,)

In [80]:
a3.shape

()

In [88]:
amatrix = q.T @ q

In [90]:
amatrix

array([[0.15241807, 0.09205202, 0.14145311],
       [0.09205202, 0.35280472, 0.42547449],
       [0.14145311, 0.42547449, 0.60623933]])

In [91]:
from scipy.linalg import inv as ii

In [92]:
ii(amatrix)

array([[  8.44236587,   1.12523683,  -2.75956768],
       [  1.12523683,  18.60163231, -13.3176584 ],
       [ -2.75956768, -13.3176584 ,  11.64007846]])

In [93]:
np.linalg.inv(amatrix)

array([[  8.44236587,   1.12523683,  -2.75956768],
       [  1.12523683,  18.60163231, -13.3176584 ],
       [ -2.75956768, -13.3176584 ,  11.64007846]])